scope: postgres
namespace: /db/
name: cloudnative01
restapi:
    listen: 10.10.3.137:8008
    connect_address: 10.10.3.137:8008
etcd3:
    hosts: 10.10.3.191:2379,10.10.3.220:2379,10.10.3.137:2379
bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
        use_pg_rewind: true
    pg_hba:
    - host replication replicator 10.10.3.137/0 md5
    - host replication replicator 10.10.3.138/0 md5
    - host replication replicator 10.10.3.139/0 md5
    - host replication all  0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5
postgresql:
    listen: 10.10.3.137:5432
    connect_address: 10.10.3.137:5432
    data_dir: /u01/pgsql/17
    bin_dir: /usr/pgsql-17/bin
    authentication:
        replication:
            username: replicator
            password: replicator
        superuser:
            username: postgres
            password: postgres
    parameters:
        unix_socket_directories: '/run/postgresql/'
watchdog:
  mode: required
  device: /dev/watchdog
  safety_margin: 5
tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
